name: 运行CLI
on:
  schedule:
    - cron: '0 18 * * *' # 每天 18:00 (UTC) 运行
  push:
    branches:
      - cli
  pull_request:
    branches:
      - cli
jobs:
  run-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: 部署代码
        uses: actions/checkout@v4
      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: 缓存 Rust 依赖
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: 构建并运行 CLI
        run: cargo run --release
